AllCops:
  Exclude:
    - 'gem_template.gemspec'
    - 'spec/**/*'
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 89

Documentation:
  Enabled: false

Style/VariableName:
  Enabled: false
